# Self-made R package

## Introduction {-}

In this assignment I created a R package to support my portfolio. I named it 'portfouri', which is a combination of my own name and the word 'portfolio'. The name was available, so I set up the project and the github repository to get started.

Originally, I wanted to make a package that would reduce duplicate code in my portfolio. But I couldn't really find any duplicate code. So, to make my life easier, I decided to write functions that would help me with [this assignment](https://yourilam.github.io/07_Relational_Databases.html). There are 4 functions available in this package:

A package to support my portfolio would reduce duplicated code. But scanning through my portfolio, I noticed that there wasn't a lot of code or duplicated code. Luckily, i found some in the "Relational data and databases" assignment that would work for this. The package that i made contains two functions:
<ul><li>cont_finder() -> Checks what continent the dataset sees your country in.</li>
<li>country_finder() -> Finds all the countries in a given continent.</li>
<li>life_expentancy_graph() -> Takes the difference in life expectancy, taken from countries all residing in the same continent, in the same year, and visualizes this.</li>
<li>population_finder() -> Finds the total population for the country, during the year of your choice.</li></ul>
For the manual and contents of the package, please visit [the portfouri github repository](https://github.com/YouriLam/portfouri).